TRUNCATE resorts;

INSERT INTO resorts (
    id, 
    name, 
    location, 
    image_url, 
    label, 
    elevation, 
    vertical, 
    acres, 
    trails, 
    lifts,
    snow_report_url,
    webcams_url,
    weather_url,
    lift_tickets_url,
    rentals_url
) VALUES (
    288,
    'Cataloochee Ski Area', 
    'Maggie Valley, NC', 
    'cataloochee-logo.png', 
    'cataloochee', 
    '5,400''', 
    '740''', 
    50, 
    18, 
    5,
    'https://cataloochee.com/the-mountain/snow-report/',
    'https://cataloochee.com/the-mountain/webcams/',
    'https://cataloochee.com/the-mountain/weather/',
    'https://cataloochee.com/tickets-passes/lift-tickets/',
    'https://cataloochee.com/planning/rentals/'
),(
    287,
    'Beech Mountain Resort',
    'Beech Mountain, NC', 
    'beech-logo.png', 
    'beech', 
    '5,506''', 
    '830''', 
    95, 
    17, 
    8,
    'https://www.beechmountainresort.com/mountain/winter-trail-map/',
    'https://www.beechmountainresort.com/mountain/webcams/',
    'https://www.beechmountainresort.com/mountain/weather/',
    'https://www.beechmountainresort.com/tickets-passes/winter-slope-tickets/',
    'https://www.beechmountainresort.com/lessons-and-rentals/equipment-rentals/'
),(
    290, 
    'Sugar Mountain Resort', 
    'Banner Elk, NC', 
    'sugar-logo.png', 
    'sugar', 
    '5,300''', 
    '1,200''', 
    125, 
    21, 
    8,
    'http://www.skisugar.com/trailmap/',
    'http://www.skisugar.com/cams/',
    'http://www.averyweather.com/Forecast/Sugar+Mountain',
    'http://www.skisugar.com/tickets/',
    'http://www.skisugar.com/rentals/'
),(
    285,
    'Appalachian Ski Mtn.',
    'Blowing Rock, NC',
    'app-logo.png',
    'app',
    '4,000''',
    '365''',
    27,
    12,
    6,
    'https://appskimtn.com/slope-report',
    'https://appskimtn.com/live-cams',
    'http://booneweather.com/Forecast/Appalachian+Ski+Mtn',
    'https://appskimtn.com/ski-tickets',
    'https://appskimtn.com/ski-snowboard-rentals'
),(
    284,
    'Sapphire Valley',
    'Sapphire, NC',
    'sapphire-logo.jpg',
    'sapphire',
    '3,400''',
    '200''',
    8,
    2,
    3,
    'https://skisapphirevalley.com/snow-report-ski-sapphire-nc.html',
    'https://skisapphirevalley.com/snow-report-ski-sapphire-nc.html',
    'https://skisapphirevalley.com/weather-ski-sapphire-valley.html',
    'https://skisapphirevalley.com/lift-rental-ratesl-ski-sapphire-nc.html',
    'https://skisapphirevalley.com/lift-rental-ratesl-ski-sapphire-nc.html'
),(
    289,
    'Wolf Ridge Ski Resort',
    'Mars Hill, NC',
    'wolf-logo.png',
    'wolf',
    '4,700''',
    '700''',
    72,
    15,
    5,
    'https://skiwolfridgenc.com/?page_id=1377',
    'https://skiwolfridgenc.com/?page_id=1591',
    'https://skiwolfridgenc.com/?page_id=1377',
    'https://skiwolfridgenc.com/?page_id=1422',
    'https://skiwolfridgenc.com/?page_id=1422'
),(
    232,
    'Ober Gatlinburg Ski Resort',
    'Gatlinburg, TN',
    'ober-logo.png',
    'ober',
    '3,208''',
    '600''',
    38,
    11,
    5,
    'https://obergatlinburg.com/slope-report/',
    'https://obergatlinburg.com/webcams/',
    'https://obergatlinburg.com/slope-report/',
    'https://obergatlinburg.com/skiing-snowboarding-tickets/',
    'https://obergatlinburg.com/rentals/'
),(
    180,
    'Canaan Valley Resort',
    'Davis, WV',
    'canaan-logo.png',
    'canaan',
    '4,280''',
    '850''',
    90,
    47,
    4,
    'https://www.canaanresort.com/ski-winter-activities/skiing-snowboarding/mountain-map-rules-stats/',
    'https://www.canaanresort.com/resort/webcams/',
    'https://www.canaanresort.com/ski-winter-activities/skiing-snowboarding/mountain-map-rules-stats/',
    'https://www.canaanresort.com/ski-winter-activities/skiing-snowboarding/lift-tickets/',
    'https://www.canaanresort.com/ski-winter-activities/skiing-snowboarding/lift-tickets/'
),(
    181,
    'Snowshoe Mountain',
    'Snowshoe, WV',
    'snowshoe-logo.png',
    'snowshoe',
    '4,848''',
    '1,500''',
    244,
    61,
    12,
    'https://www.snowshoemtn.com/mountain-info/mountain-report#/',
    'https://www.snowshoemtn.com/media-room/skidder-slope-live-cam',
    'https://www.snowshoemtn.com/mountain-info/mountain-report#/',
    'https://www.snowshoemtn.com/plan-your-trip/tickets-and-passes',
    'https://www.snowshoemtn.com/plan-your-trip/rentals'
),(
    182,
    'Winterplace Ski Resort',
    'Ghent, WV',
    'winterplace-logo.png',
    'winterplace',
    '3,600''',
    '603''',
    90,
    28,
    10,
    'https://www.winterplace.com/snow-report',
    'https://www.winterplace.com/mountainhouse-cam',
    'https://www.winterplace.com/snow-report',
    'https://www.winterplace.com/lift-tickets',
    'https://www.winterplace.com/rentals'
),(
    196,
    'Bryce Resort',
    'Basye, VA',
    'bryce-logo.jpg',
    'bryce',
    '1,750''',
    '500''',
    25,
    8,
    5,
    'https://bryceresort.com/mountain-info/conditions',
    'https://bryceresort.com/winter/ski-and-snowboard',
    'https://bryceresort.com/winter/ski-and-snowboard',
    'https://bryceresort.com/winter/ski-and-snowboard',
    'https://bryceresort.com/winter/ski-and-snowboard'
),(
    197,
    'Massanutten Resort',
    'Massanutten, VA',
    'massanutten-logo.png',
    'massanutten',
    '2,925''',
    '1,110''',
    70,
    18,
    7,
    'https://www.massresort.com/play/snow-sports/snow-conditions/',
    'https://www.massresort.com/play/snow-sports/snow-webcams/',
    'https://www.massresort.com/play/snow-sports/weather/',
    'https://www.massresort.com/play/snow-sports/',
    'https://www.massresort.com/play/snow-sports/hours-rates/'
),(
    198,
    'The Omni Homestead Resort',
    'Hot Springs, VA',
    'omni-logo.jpg',
    'omni',
    '3,200''',
    '700''',
    45,
    10,
    2,
    'https://www.omnihotels.com/hotels/homestead-virginia/property-details/weather',
    'https://www.omnihotels.com/hotels/homestead-virginia',
    'https://www.omnihotels.com/hotels/homestead-virginia/property-details/weather',
    'https://www.omnihotels.com/hotels/homestead-virginia',
    'https://www.omnihotels.com/hotels/homestead-virginia'
),(
    199,
    'Wintergreen Resort',
    'Wintergreen, VA',
    'wintergreen-logo.png',
    'wintergreen',
    '3,512''',
    '1,003''',
    125,
    24,
    8,
    'https://www.wintergreenresort.com/Slopes/',
    'https://www.wintergreenresort.com/Mountain-Cam/',
    'https://owc.enterprise.earthnetworks.com/OnlineWeatherCenter.aspx?aid=7184',
    'https://www.wintergreenresort.com/Lift-Tickets/',
    'https://www.wintergreenresort.com/Rentals/'
),(
    557,
    'Cloudmont Ski Resort',
    'Mentone, AL',
    'cloudmont-logo.jpg',
    'cloudmont',
    '1,800''',
    '150''',
    9,
    2,
    2,
    'https://www.snocountry.com/resort-page/al/cloudmont',
    'https://www.snocountry.com/resort-page/al/cloudmont',
    'https://www.snocountry.com/resort-page/al/cloudmont',
    'http://www.cloudmont.com/conditions.html',
    'http://www.cloudmont.com/conditions.html'
);




