TRUNCATE resort;

INSERT INTO resort (
    id, 
    name, 
    location, 
    image_url, 
    label, 
    elevation, 
    vertical, 
    acres, 
    trails, 
    lifts,
    snow_report_url,
    webcams_url,
    weather_url,
    lift_tickets_url,
    rentals_url
) VALUES (
    288, 
    'Cataloochee Ski Area', 
    'Maggie Valley, NC', 
    'cataloochee-logo.png', 
    'cataloochee', 
    '5,400''', 
    '740''', 
    50, 
    18, 
    5,
    'https://cataloochee.com/the-mountain/snow-report/',
    'https://cataloochee.com/the-mountain/webcams/',
    'https://cataloochee.com/the-mountain/weather/',
    'https://cataloochee.com/tickets-passes/lift-tickets/',
    'https://cataloochee.com/planning/rentals/'
),(
    287,
    'Beech Mountain Resort',
    'Beech Mountain, NC', 
    'beech-logo.png', 
    'beech', 
    '5,506''', 
    '830''', 
    95, 
    17, 
    8,
    'https://www.beechmountainresort.com/mountain/winter-trail-map/',
    'https://www.beechmountainresort.com/mountain/webcams/',
    'https://www.beechmountainresort.com/mountain/weather/',
    'https://www.beechmountainresort.com/tickets-passes/winter-slope-tickets/',
    'https://www.beechmountainresort.com/lessons-and-rentals/equipment-rentals/'
),(
    290, 
    'Sugar Mountain Resort', 
    'Banner Elk, NC', 
    'sugar-logo.png', 
    'sugar', 
    '5,300''', 
    '1,200''', 
    125, 
    21, 
    8,
    'http://www.skisugar.com/trailmap/',
    'http://www.skisugar.com/cams/',
    'http://www.averyweather.com/Forecast/Sugar+Mountain',
    'http://www.skisugar.com/tickets/',
    'http://www.skisugar.com/rentals/'
);